### ISSUE TITLE
kq2ShadeFollowUp assumes Shade was sexed even if that didn't happen.

### ISSUE THREAD

**Issue by Tyrn-11** [OXOIndustries/Trials-in-Tainted-Space#1000]
If Shade was distracted by fliting(and without the follow-up-intercourse) and subsequently defeated during KQ2(but not killed ofc), the function kq2ShadeFollowUp in includes/events/karaquest2/content.as has Shade acting like she was sexed during the distraction.

The wiki makes mention that '_Relationships outside of being her lover are yet to be implemented_' , is this the case here as well?

**Comment by Jacques00** [comment]
Well, since there wasn't an alternative path for Shade's content, I'll have to disable her completely... Or that is, to be accurate, set her to be "hostile"--which means she will no longer be interacted with and won't invite Steele to Uveto (for obvious reasons), but she may appear in future content involving Astra on Uveto.

The wiki bit might be an out-of-date line that wasn't edited.

**Comment by Tyrn-11** [comment]
So with this, the only way to get Shade to Uveto and have her remain friendly without sexing her, is to trigger her probe-event and not reveal who her father is(before doing KQ2)?

I noticed a bug in the kq2ShadeFollowUpAmends() function in the same file(includes/events/karaquest2/content.as); 
This part is upside-down:

`// if Probe Dungeon Not Done:
if(flags["MYRELLION_PROBE_CASH_GOT"] != undefined){
...
}
// if Probe Dungeon done:
else
{
...
}`

Because MYRELLION_PROBE_CASH_GOT is not undefined when the Probe dungeon is done(so it should be `flags["MYRELLION_PROBE_CASH_GOT"] == undefined`).

Should I open a new issue for this?

**Comment by Tyrn-11** [comment]
Just a small thing, but i looked at your fix and noticed this check:
if(!shadeIsSiblings() && !shadeIsLover())
you added in includes/events/karaquest2/content.as.

That check is not required, since both conditions will always be the met(if shade is a sibling, she won't be at myrellion anymore, so she won't appear in KQ2 and this talk will never happen. And shadeIsLover is only true if she was sexed, which can't be the case, because we check for if (flags["SEXED_SHADE"] == undefined) at the beginning of the section).

**Comment by Jacques00** [comment]
Yes, I am aware, but because the relationship branches variations are so complex, I added them there as a "just in case" check--it wouldn't normally land on those if the route to unlock that scene happens, but ya never know!
