### ISSUE TITLE
Stat Bar Updates Lagging After Lots of Input

### ISSUE THREAD

**Issue by Fenoxo** [OXOIndustries/Trials-in-Tainted-Space#294]
This may be a more endemic problem than I've discovered, but there's not a lot of places it would come up.

If the lust bar is raised/lowered multiple times throughout a scene, it can lag and not update until the next scene. Most notably, while I was fiddling with the milking scenes, I was able to get the lust bar not to drop from orgasm until the scene AFTER the masturbation scene.

This has been a long-standing issue.

**Comment by Fenoxo** [comment]
It might be from having a lust adjustment after processTime that is in the opposite direction of processtime's lust adjustment.

**Comment by Gedan** [comment]
Please to clarify a scene function specifically that I can fuck around to figure this out with.

**Comment by Fenoxo** [comment]
Originally had it showing up during a lactation scene I was fucking with but can't seem to recall how to set that off again. It does seem to happen sometimes with Irellia's quad-titfuck scene if I click through too fast.

Post-scene: http://puu.sh/g3328/68f9a34ec0.png
Press inventory or something: http://puu.sh/g3339/dd4b97b5ff.png

**Comment by Gedan** [comment]
Still totally, completely unable to replicate.

**Comment by Gedan** [comment]
I think I might have solved this recently as part of some fuckery I made with how and when stat updates are pushed to the UI. Basically, any player input should now push through an updated set of stats just after executing the scene-target the player just selected, so the UI stats should always match up with anything happening in the scene presently being displayed every time.
