### ISSUE TITLE
goo transformation? save/move bug and snake penises bug

### ISSUE THREAD

**Issue by thenonamezz** [OXOIndustries/Trials-in-Tainted-Space#521]
after getting all penises (one of each exept snake (snake show no text) and terrain) and vaginas (with 5 clits on each)
then i cant save or move

**Comment by Jacques00** [comment]
The snake penis is a bug that had to do with the output issue (same with the balls). This has been fixed in the pull request #519.

I'm not sure what your moving problem is though. You might need to provide more details.

**Comment by thenonamezz** [comment]
the moveing problem is that theres no buttons to press

**Comment by Fenoxo** [comment]
I'm assuming he used the goo menu and hit some of the old bugs with it.
