### ISSUE TITLE
[Easy Fix] Gene's Blowjob

### ISSUE THREAD

**Issue by noobsaleh** [OXOIndustries/Trials-in-Tainted-Space#536]
flags["GENE_BLOWJOB"] is checked but never set or incremented in the game. This results in an entire scene (of Gene's) that can't be accessed.

See Line 803 in genesmods.as

The flag should be set or incremented at the end of the genesModsBlowjob() function.

**Comment by Jacques00** [comment]
Should be taken care of in the pull request (#535). Thanks for the report!
