### ISSUE TITLE
Wrong variable used in scene?

### ISSUE THREAD

**Issue by Garzhad** [OXOIndustries/Trials-in-Tainted-Space#549]
While grepping to look for what's needed for various scenes, came across this. Since it's talking about your Cock in the scene, I imagine you meant to check for cockvolume not biggest tit size.\

In bathhouse.as:

00779: {
00780: if(pc.cockTotal() >= 4) output(" Your terrible tangle of pricks stuns her. <i>a??How... how do you even get anything done with so many of these?a??</i> she asks, fruitlessly trying to separate them.");
00781: else if(pc.cockTotal() >= 2) output(" She passes lightly over one turgid shaft, then stops when she finds a second, adding more hands to make sure she didna??t miscount. a??<i>My goodness. Are you routinely expected to mate multiple females on your world?a??</i>");
**00782: else if(pc.biggestTitSize() >= 400) output(" Her hands slide up your [pc.cockBiggest], moving as if they expect to caress a crown which never comes. <i>a??This is... so big. I shudder to imagine the females of your homeworld,a??</i> she remarks, innocently.");**
00783: else output(" She strokes your cock once, then brushes your tip with her palm. <i>a??Ah, so you are a male.a??</i>");
00784: }

Amending this with another wrong variable, this one with with Aliss. Should be less than(<=) not greater than for it to make sense; why would your asshole be spacious and gaped if it's LESS than her cock volume, whilst resisting and clamping shut when it's Greater?

In Aliss.as:

01260: **else if(pc.analCapacity() >= chars["ALISS"].cockVolume(0))** output("Your asshole resists, reflexively attempting to clamp shut as the anal invader inches forward. You bite your lip as Aliss grunts, thrusting in with one smooth motion.");
01261: else output("Your spacious and gaped asshole yawns widely as Aliss thrusts forward, engulfing her alien cock in one smooth motion.");

And further down in said file:
01267: **else if(pc.analCapacity() >= chars["ALISS"].cockVolume(0))** output("Your ass is squeezing me just right.");
01268: else output("Mmm, you certainly have a cock hungry ass, don't you?");

**Comment by Jacques00** [comment]
Implemented fixes.
