### ISSUE TITLE
Mini map bug

### ISSUE THREAD

**Issue by Garzhad** [OXOIndustries/Trials-in-Tainted-Space#566]
This.... seems really minor and doesn't actually Break anything that I have noticed, but it still struck me as very odd how a 'block' on the mini map just completely vanishes at this point. Haven't seen that before, decided to report anyway.
![bug2](https://cloud.githubusercontent.com/assets/6739576/12310082/43922d58-ba1c-11e5-9d85-1d683e9386b5.jpg)
![bug1](https://cloud.githubusercontent.com/assets/6739576/12310081/4384832e-ba1c-11e5-9873-08f8189cd2ad.jpg)

**Comment by Jacques00** [comment]
This happens with the Novahome tiles while in the wilds of Tarkus as well.

**Comment by Gedan** [comment]
Found it; one of the rooms was referencing another incorrectly. The room itself isn't disappearing, it's drawing itself in the wrong place dependant on where you are on the map, so there's actually two rooms drawn over each other.

Fix in 895f28a (soon™)
