### ISSUE TITLE
Flahne exhibition scenes

### ISSUE THREAD

**Issue by cpt-jack** [OXOIndustries/Trials-in-Tainted-Space#568]
>> *if(flags["FLAHNE_EXHIBITIONISM_UNLOCKED"] == 1 && flags["FLAHNE_DESK_DISABLED"] == undefined)*

flahne.as line 439
it's not really a bug, but if you should ever add the possibility of getting the exhibition scenes back after you pissed flahne of the check should be for
*flags["FLAHNE_DESK_DISABLED"] == 0*
instead of
*flags["FLAHNE_DESK_DISABLED"] == undefined*

**Comment by Gedan** [comment]
More complicated; would have to check for both (undefined is weird and doesn't always coerce to 0 in boolean logic, depending on how AS3 feels at the time).

**Comment by cpt-jack** [comment]
hm interesting, but also quite annoying, thanks for the info
