### ISSUE TITLE
Can't get the girl

### ISSUE THREAD

**Issue by argenten** [OXOIndustries/Trials-in-Tainted-Space#571]
Emmy's quest progression isn't happening after her flower is given. She sends the email but she does not acknowledge that Steele has read it or even give her name for the next quest.

**Comment by Jacques00** [comment]
You need to buy at least one item from her shop, I think.

**Comment by argenten** [comment]
duh, I spaced on that. Thanks for bearing with me, I'll check on that making a difference.
