### ISSUE TITLE
thollum.as errors

### ISSUE THREAD

**Issue by Zeikfried** [OXOIndustries/Trials-in-Tainted-Space#579]
gleaned these by reading the source code directly; line numbers are as of 1/20/16:

line 211 -- if(pc.isBimbo()) 
//bro should be included in bim or excluded from misch

line 264 -- else if(pc.isBro()) output("\n\n<i>“Well, ");
</i>//looks like Fen wanted to add something specific for bro here and forgot to finish; italics tag is also left open

line 586 -- addDisabledButton(2,"Audit Class","Audit Class","Yarasta’s class is in recess right now. It’d be creepy if you just sat in the back alone and stare.");
//should be 'stared'

line 642 -- if(pc.isBimbo()) output("<i>“You used to get people past all those guards? You’re, like, really smart.”</i>");
//include bro in bim or exclude from misch

line 777 -- if(pc.isBimbo())
//expand to bro

line 871 -- if(pc.lust() < 33) addDisabledButton(0,"Flirt","Flirt","Maybe you’ll try that when your more in the mood.");
//change 'your' to 'you're'

line 1398 -- else if(pc.isMischievous())
//exclude bro

line 1490 -- if(pc.isBimbo()) 
//expand to bro

line 1682 -- if(pc.isBimbo()) 
//include bro in bim or exclude it from nice and misch

line 2147 -- if(cLength > 5) output("you can see her adam’s apple bulge just before ");
//capitalize to 'Adam's apple'

also, the buttons 'Check In', 'TakeTheTour', 'Yarasta' don't seem to have their tooltips

**Comment by Fenoxo** [comment]
The ones I cut the bro check from sound way too feminine and note at all
right for brute speech. Brute speech is supposed to be short, to the point
the statements, not just a deeper-voiced version of bimbo insanity.

**Comment by Zeikfried** [comment]
I observed the trend and agree in places. But some untreated outputs are too eloquent, slangy, or quick-witted for bro speech.

If bro speech is just terse instead of flavored with a little stupidity and shallowness, it doesn't register as different enough from asshole speech to be worth including to me. I updated the list with your guidelines in mind and kept numbers that could be prudently adjusted and aren't feminine. Would you have a look?

**Comment by Zeikfried** [comment]
New line 1702 needs to check for either bimbo or bro to accommodate the changes there.

New line 1714 should say "Fair's fair" instead of "Fairs fair".

Otherwise, everything looks great.
