### ISSUE TITLE
0.6.31 Elevator No Worky

### ISSUE THREAD

**Issue by Fenoxo** [OXOIndustries/Trials-in-Tainted-Space#583]
In our constant fiddling, we have apparently broken the deck 13 elevator again, according to patreon comments.

"Deck 13 lift doesn't work, picked up the Anno quest for another sample of grey goo, and can't return."

**Comment by Jacques00** [comment]
They need to be more specific--there are certain parts of Anno quest where the elevator is disabled. It shouldn't work before or during the quest, but should activate after the quest is complete and Tarkus is not destroyed. There should be a clue to why the elevator doesn't work in the text.

If Tarkus is destroyed and they are specifically looking for the gray goo armor, they should head to the Myrellion bar after talking to Anno about the Nova Update.

**Comment by Jacques00** [comment]
K, applied an alternate fix for the issue--but the conditions are still the same (Anno's mission has to be completed and the shields have to be on when/if Tarkus explodes, otherwise the elevator is not usable).
