### ISSUE TITLE
Error: Error #1502

### ISSUE THREAD

**Issue by Darkwolfdemon** [OXOIndustries/Trials-in-Tainted-Space#584]
Level 8. Flying back and forth between Tarkus and Myrellion to kill time to get an email. When get to Myrellion this appears.

Version: 0.6.31

Error: Error #1502
	at classes.UIComponents.MiniMap::MiniMap/setMapData()
	at classes::GUI/setMapData()
	at classes::TiTS/mainGameMenu()
	at classes::GUI/PressButton()
	at classes::TiTS/pressButton()
	at Function/()
	at classes::BoundControlMethod/ExecFunc()
	at classes::InputManager/ExecuteKeyCode()
	at classes::InputManager/KeyHandler()

**Comment by Jacques00** [comment]
Was there any text printed before that error?

**Comment by Darkwolfdemon** [comment]
There was some. But it was the usual text that one would see when flying to myrellion. I apologize, I am not sure which part it is though.

**Comment by Jacques00** [comment]
Is this bug repeatable, and if you can detail any status effects your character might have had (or provide a save file before the bug occurred), that might be helpful.

**Comment by Darkwolfdemon** [comment]
I flew back and forth maybe 40 times or more, did not get it again. I did not notice anything when I got that error. Enclosed is the save file I had some time before I got the error.
[Save4.zip](https://github.com/OXOIndustries/Trials-in-Tainted-Space/files/102476/Save4.zip)

**Comment by Jacques00** [comment]
I cannot seem to replicate this bug both with and without your save file. If it happens again, feel free to add to this report or make a new one.

**Comment by Darkwolfdemon** [comment]
Sure. Thank you
