### ISSUE TITLE
RUN AWAY!

### ISSUE THREAD

**Issue by argenten** [OXOIndustries/Trials-in-Tainted-Space#585]
As the Monty Python homaging title hints, after the Juggernaut I tried to go to the lobby so I could get some energy drinks before Amara's battle and I got this.

T"he elevator connects three floors of the Black Void base: the research level, the main level above, and a helipad on the roof.

The roof’s been caved in, and a dead pirate in massive armor lies on the floor of the car. You’re amazed the elevator is still functional.

Something bad happened!

Please report this message, and include any prior scene text or a description of what you did before seeing this message:

Version: 0.6.31

TypeError: Error #1010
	at classes::TiTS/move()
	at classes::TiTS/buttonClick() "

**Comment by Jacques00** [comment]
There was a typo to a room name that probably caused it.
