### ISSUE TITLE
Emails from Celise?

### ISSUE THREAD

**Issue by velociceratops** [OXOIndustries/Trials-in-Tainted-Space#593]
Hey, I'm not a big fan of celise, so I didn't take her after the tutorial finished, but i still got the OOGABOOGA email from her.

**Comment by Jacques00** [comment]
From which version? This should be fixed in a previous pull request commit, at least for the latest backer build, I think.

https://github.com/OXOIndustries/Trials-in-Tainted-Space/commit/0eececb3ae14da1d494aa836c37db99248923613

**Comment by velociceratops** [comment]
I started a new game on thursday, so whichever version was available off fenoxo.com that day. I just got the Celise underwear email too.

**Comment by Fenoxo** [comment]
Well, fenoxo.com is older than Jacques00's commit, so I'm gonna call this case closed. Be sure and check it out in a week or so when the next live build hits.
