### ISSUE TITLE
Tam fight gets output text stuck in bold

### ISSUE THREAD

**Issue by Ikazoid** [OXOIndustries/Trials-in-Tainted-Space#595]
When fighting Tam and her turrets, I find that the output text gets stuck in bold if she uses her disruptor attack. This persists after the fight, until I reload the .swf file. I'm using the latest build, but I checked the 0.6.31 version as well and the same thing happens. Interestingly, the text of my action that is printed before the disruptor attack gets bolded as well, no matter which I choose. This glitch doesn't affect things like the Codex screen text or the Appearance screen text, just the primary output. I've been looking all over the code for a cause but haven't come up with anything.

Attached is my save from just before the fight
[Skia - 25 days.zip](https://github.com/OXOIndustries/Trials-in-Tainted-Space/files/111555/Skia.-.25.days.zip)

**Comment by Fenoxo** [comment]
Thanks for the report. I'll try and get 'round to this tomorrow sometime.

**Comment by Fenoxo** [comment]
Fixt via fcbcf341df35f1fb909bed45748ecd80c2addddb though I'm not sure exactly why.

**Comment by Gedan** [comment]
See 84db913 for theories.
