### ISSUE TITLE
Ovilium may possibly need some slight balancing...

### ISSUE THREAD

**Issue by Grethos** [OXOIndustries/Trials-in-Tainted-Space#600]
After taking Ovilium (my character has two wombs so I took two doses), being intimate with Bess (my Bess is equipped with a cock attachment) results in four of those egg multiplication messages. And since the intimacy with Bess is so short in terms of the minutes it takes to finish the scene, I tried being intimate with her as the pitcher about seven times in a row then checked my stats screen to see how the eggs were progressing after all those multiplication messages. This is what I found:

Belly
* Belly, Size Rating, Total: 4369257.625
* Belly, Weight: 4587720.506 lbs (20182 %)
* Active Pregnancies, Total: 2
First Womb
* Belly, Size Rating: 2398670.75
* Pregnancy, Type: Ovilium, Eggs
* Pregnancy, Gestation Time: 1 hour 45 minutes
* Pregnancy, Incubation Speed Modifier: 300 %
* Pregnancy, Egg Count: 11156303
Second Womb
* Belly, Size Rating: 1970586.875
* Pregnancy, Type: Ovilium, Eggs
* Pregnancy, Gestation Time: 1 hour 30 minutes
* Pregnancy, Incubation Speed Modifier: 300 %
* Pregnancy, Egg Count: 10529397

After birthing the 21.6 million eggs, my belly went back to normal:

Belly
* Belly, Size Rating: 0
* Belly, Weight: 0 lbs

**Comment by Netys** [comment]
Also:
* Wetness bonus is very substantial. Generally wetness is never above 5. And egg can give 1-2 to wetness, up to 100.
* Preggcelleration can bypass stage progression events. I'd recommend pregnancyIncubationMulti bonus.
