### ISSUE TITLE
Multipregnancy multimessage

### ISSUE THREAD

**Issue by Fenoxo** [OXOIndustries/Trials-in-Tainted-Space#602]
So while testing the egg trainer, I got my character full of butt eggs and vag eggs. I expected to see single alert I had put in show up twice.

It showed up more than that. Might be an issue with how those events are queued with multiple pregnancies or multiple pregnancies of the same time.

Textdump:
[7:59:56 PM] Bronoxo: Kira’s log:

Your progress is interrupted by a sudden shift in your pregnant belly, making you nearly double over with intense, overwhelming pleasure. Just feeling the dozens eggs moving around inside you, jiggling with your movements, is almost enough to make you cum on the spot. You bite your lip and hold on, ignoring the curious looks from passersby.

Your body’s betrayal lasts only for a moment before the eggs settle down again. You sigh, taking a deep breath to steady yourself before you get going again, a little more flushed than before.

Your progress is interrupted by a sudden shift in your pregnant belly, making you nearly double over with intense, overwhelming pleasure. Just feeling the dozen eggs moving around inside you, jiggling with your movements, is almost enough to make you cum on the spot. You bite your lip and hold on, thankful that you’re all alone.

Your body’s betrayal lasts only for a moment before the eggs settle down again. You sigh, taking a deep breath to steady yourself before you get going again, a little more flushed than before.

Your progress is interrupted by a sudden shift in your expectant belly, making you nearly double over with intense, overwhelming pleasure. Just feeling the dozens eggs moving around inside you, jiggling with your movements, is almost enough to make you cum on the spot. You bite your lip and hold on, ignoring the curious looks from passersby.

Your body’s betrayal lasts only for a moment before the eggs settle down again. You sigh, taking a deep breath to steady yourself before you get going again, a little more flushed than before.

Your progress is interrupted by a sudden shift in your expectant belly, making you nearly double over with intense, overwhelming pleasure. Just feeling the dozen eggs moving around inside you, jiggling with your movements, is almost enough to make you cum on the spot. You bite your lip and hold on, thankful that you’re all alone.

Your body’s betrayal lasts only for a moment before the eggs settle down again. You sigh, taking a deep breath to steady yourself before you get going again, a little more flushed than before.

Your progress is interrupted by a sudden shift in your round belly, making you nearly double over with intense, overwhelming pleasure. Just feeling the dozen eggs moving around inside you, jiggling with your movements, is almost enough to make you cum on the spot. You bite your lip and hold on, thankful that you’re all alone.

Your body’s betrayal lasts only for a moment before the eggs settle down again. You sigh, taking a deep breath to steady yourself before you get going again, a little more flushed than before.

**Comment by Fenoxo** [comment]
Obviously I devised a work-around, but this could still be indicative of a problem.

**Comment by Gedan** [comment]
Ye, this is mostly an unfortunate consequence of how time passage happens in general, combined with the potential for multi pregnancies and not wanting to add simplicity at the cost of finite control.

The way I've been dealing with this is to use the core things in the pregnancy handlers to control the presence of transient status effects or flags (the way I've been doing it has refined over time). How I use them depends on how the pregnancy has been written, but probably the easiest to grok is to use one as a latch; only add an event to the list of queued events if the effect doesn't exist, else do nothing- when the event actually gets executed at some point later down the line, remove the effect as part of that.

Handling the deferment properly is hella messy though, with a lot of closures to ensure the proper variables are passed around and exist when the message is actually going to be displayed.

**Comment by Gedan** [comment]
Renvras pregnancy types are a good example of it iirc, because there are two types that share a lot in common, so transient statuses convey limitations on how much stuff they jam into the event queue.
