### ISSUE TITLE
Combat Crash

### ISSUE THREAD

**Issue by Fenoxo** [OXOIndustries/Trials-in-Tainted-Space#627]
http://orig08.deviantart.net/d304/f/2016/050/5/d/bandicam_2016_02_19_21_45_56_629_by_monkitteh_adopts-d9sb4cb.jpg

Sent to me via Patreon by Tesah.

**Comment by Fenoxo** [comment]
Does this fix this one?

"I started a new game and couldn't get past the celise fight. Hitting 'attack' caused the following error in the tutorial. ReferenceError: Error #1056
	at classes.GameData::CombatContainer/selectSimpleAttack()
	at classes::TiTS/buttonClick()"

Also did you test to see if your fix works?

**Comment by Jacques00** [comment]
Yes, it fixes both and any other instances I could find. If there's another crash, then I might have missed another one somewhere else, or it's unrelated to this particular issue. But yes, I remember Varmints and Celise being the main two who were left out.
