### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by ankser** [OXOIndustries/Trials-in-Tainted-Space#634]
1) function classes.Creature.vanaescore
if (totalVaginas(GLOBAL.TYPE_VANAE)>totalVaginas()) counter++;
Is it possible to have more vanae vaginas than total vaginas?

2) function includes/tavros/OviliumBonus.oviliumEffects
var hasEmptyWomb:Boolean = (pc.totalPregnancies() <  pc.totalVaginas());
Why I can't get it with one non-pregnant vagina and butt pregnancy? I don't want to break EggTrainerFauxEgg prtegnancy for this (really long waiting till required effect), but looks like I have to.

**Comment by Jacques00** [comment]
The vanae issue was a typo that I'm pretty sure I fixed a some merges ago.

The empty womb check was something left over after I had reorganized how all the other checks worked in concert with one another and I forgot to remove it. It should be fixed in the pull request.
