### ISSUE TITLE
Select a class bug

### ISSUE THREAD

**Issue by Monkitteh** [OXOIndustries/Trials-in-Tainted-Space#636]
I just got the backers build and went to load a save and it wouldn't load, so decided to make a new level and encountered a similar bug to the one that was my save 
http://orig01.deviantart.net/741f/f/2016/058/3/e/bandicam_2016_02_28_01_01_11_244_by_monkitteh-d9t9yqb.jpg
http://orig09.deviantart.net/93b9/f/2016/058/e/7/bandicam_2016_02_28_01_01_23_331_by_monkitteh-d9t9yq4.jpg
I figured this is a huge issue and probably needs to be fixed asap

**Comment by Fenoxo** [comment]
This should be fixed in 0.6.39. Please post if it has not.
