### ISSUE TITLE
Permanent Breasts

### ISSUE THREAD

**Issue by SpaceFu** [OXOIndustries/Trials-in-Tainted-Space#637]
My male character grew C-cup breasts during pregnancy with the Deep Lake Queen's eggs and began lactating. After waiting out the pregnancy and waiting for the lactation to stop I visited Dr. Lash to get a rack removal, and while the dialogue said that my character's breasts were removed, visiting the character description page reveals he still possesses C-cup breasts, and other scenes still treat him as having breasts, including Dr. Lash. Other methods of breast removal (Uthra sap, Man Up) also claim that breast size decreases, yet they remain at C-cup level and refuse to go away.

EDIT: This is using game version 0.6.33

**Comment by Fenoxo** [comment]
Please to be providing your save file.

**Comment by SpaceFu** [comment]
How/where do I do that?

**Comment by Fenoxo** [comment]
Open game. save to file, exit game, upload save file to file hosting
service of your choice, link here.

**Comment by SpaceFu** [comment]
https://www.dropbox.com/s/52yqk1s2fqx73mz/Robin%20-%2093%20days.tits?dl=0
 This should be it.

**Comment by Fenoxo** [comment]
Thanks. Looks like there could be a few culprits, but just to be certain the game should re-set your boob swelling amount every hour or so to correct values - which in this character's case is 0.

Also Dr. Lash's surgery should instantly stop lactation in the future.
