### ISSUE TITLE
Not nuki nuts perk but Cum doesnt store up over time

### ISSUE THREAD

**Issue by MillaSteele** [OXOIndustries/Trials-in-Tainted-Space#640]
no longer does whuts its intended to do. nothing happens when waiting for hours even days in game

**Comment by Fenoxo** [comment]
RIP-py nuts

**Comment by MillaSteele** [comment]
on further inspection its not the perk but the fact that your cum isnt storing up over time at all 
Cum, Capacity: 0 %
* Cum, Current Internal: 0 mLs
* Cum, Probable Ejaculation:  1000 mLs
* Cum, Max: 1296 mLs

that is whut i get at all times on a current build and new characters

**Comment by Fenoxo** [comment]
Fixt via 4dcac24923b1a94c3677246be368b87b1e22b3f8
