### ISSUE TITLE
ver 6.39 possible Ellie bug

### ISSUE THREAD

**Issue by Feralcus** [OXOIndustries/Trials-in-Tainted-Space#646]
Ellie seems to no longer acknowledge my PCs penis.

My character is a gooey (Three doses galomax I think) half leithan that started male but added a vag with goo. Penis size is 26in which should fit just fine in a taur... So I don't think its a "dick too big error" but maybe. Have taken the treatment which seems to have gone the feminine route as well if that matters.

“Well, since you don’t have a big, throbbing bulldick to stick in me, I guess I’ll just have to return the favor the old-fashioned way, won’t I?”

Am I just exceeding her capacity or is this a bug?

**Comment by Feralcus** [comment]
Nvm, it was a dick too big error. 
Although I have to say 22 inches max capacity is a bit small for a taur I would think...

**Comment by Fenoxo** [comment]
Looks like she'll take any size of dick according to the code - it just randomly picked the vag scene. I'm gonna adjust the intro to work better.
