### ISSUE TITLE
Wrong variable used in scene

### ISSUE THREAD

**Issue by Garzhad** [OXOIndustries/Trials-in-Tainted-Space#648]
In Renvra.as a conditional check calls for cockvolume when logically it should be **if(!pc.hasKnot(x))** (I think thats the right call anyway) 
Lines and context:

00611: if (pc.hasKnot()) output(", spurred on by the sudden impact of your [pc.knot] pounding her wide open, tying the two of you together");
00612: output(". Short, frantic thrusts bring you deeper into her, working out every drop of spooge you can fill her with. By the time you're done, Renvra's left panting against the wall, her hands cradling the throbbing shaft of her deflating cock against her belly. She's a mess of her own pink spunk, smearing across her chest and shoulders and dripping down onto her desk.");
00613: output("\n\n<i>a??What a mess,a??</i> she laughs, rolling her head back and closing her eyes. A plated finger flicks through the pink cream on one of her tits, bringing it up to her mouth to be cleaned off. After a momenta??s enjoyment of her own taste, Ren reaches into a shelf nearby, pulls out a fairly thick towel, and begins to clean herself off -- even as youa??re still ");
**00614: if(pc.cockVolume(0) < 300) output("buried");
00615: else output("knotted");**
00616: output(" inside her.");

I've also noticed a bit of discrepancy in the Anno/Kaede bar sex scene. In Anno.as:

03603: **if (pc.biggestCockLength() <= 12) output(" bottom out inside Kaedea??s tight backdoor");**
03604: else output(" push as much of your cock into Kaedea??s tight backdoor as you can");
03607: output("\n\nFor your part, you let yourself rest inside the halfbreed for a long moment, trying to catch your breath before you slowly start to withdraw. You give her a few tentative thrusts after that, nice and slow... but you cana??t settle for that much longer. Anno gives you an approving nod as your pace increases, steadily gaining speed and power with every");
03608: **if (pc.biggestCockLength() <= 10)**
03609: {
03610: **if (pc.balls > 0) output(" balls-deep");
03611: else output(" hilting");**
03612: }
03613: else output(" gut-straining");

That a misprint or does Kaede's colon suddenly contract and get 2 inches shorter in those 30 seconds, or is there some other reason for that?

Noticed another thing, this time regarding Bess. Namely, it seems like someone mistook cThicknessRatioRaw to mean Actual cock diameter instead of Ratio as it actually is. Meaning when Bess uses the Saurian cock with its length of 20 and thickness ratio of 3 what you get is a dick that's 20" long and 10" in diameter for a literal block of cock with a volume in excess of 1000, as opposed to the implied desired size of 20" long by 3" wide, though even with a ratio of 1 it'd still be at least 3 1/3" wide.

Examples: 
03036: if (!bess.hasCock()) bess.cocks.push(new CockClass());
03037: bess.cocks[0].cType = GLOBAL.TYPE_SAURIAN;
03038: bess.cocks[0].cLengthRaw = 20;
**03039: bess.cocks[0].cThicknessRatioRaw = 3;**

03056: {
03057: if (!bess.hasCock()) bess.cocks.push(new CockClass());
03058: bess.cocks[0].cType = GLOBAL.TYPE_EQUINE;
03059: bess.cocks[0].cLengthRaw = 16;
**03060: bess.cocks[0].cThicknessRatioRaw = 2.5;**

**Comment by Fenoxo** [comment]
Fixed via caa6750f9ec7d59f79e20e7d088b6a0a41c3dc9e

**Comment by Garzhad** [comment]
I found and amended it with another problem I had seen, did you get that one?

**Comment by Fenoxo** [comment]
Fixed. Please use multiple issue reports for multiple issues.
