### ISSUE TITLE
Naleen nip: cock TF "failed"

### ISSUE THREAD

**Issue by ankser** [OXOIndustries/Trials-in-Tainted-Space#649]
If all cocks are already of naga type, it's possible to get message "... nothing happens":
if (choices.length > 0) {transform}
else if (target.cockTotals > 0) {cockTypeLockedMessage}

**Comment by Fenoxo** [comment]
I'm not sure what the bug you're trying to point out it is.

As I read it, you're saying "If your dicks are already transformed, they don't transform again" which makes 100% sense to me.

**Comment by ankser** [comment]
...they don't transform again, but message displayed about failed TF.

**Comment by ambjoorn94** [comment]
If there's nothing to change, it fails to change anything.
Sounds logical, don't you think?

**Comment by ankser** [comment]
In nearly (?) every other similar situation nothing happens and nothing messaged, so this is exception.

**Comment by Fenoxo** [comment]
if an item doesn't comment on the lack of a TF happen, it sounds like that TF is lazily coded.

**Comment by ambjoorn94** [comment]
I don't suppose you mean this small message:

"Your crotch warms, but nothing happens."

This message seems to happen with a lot of different transformatives, Horse Pill, Zil Ration, Nuki Cookies, Goblinola, Ausar Treats, Terran Treats etc.

**Comment by Fenoxo** [comment]
That indicates that it tried to TF you, but the TF was blocked by something like mimbranes, for example.

**Comment by ankser** [comment]
"Lazily coded" no applicable to situation with earlier finished TF, like here - I can't remember if any TF item messages anything about any TF finished before as failed TF.
This one will say "...nothing happens" if previous time it was successful - no cocks to TF, but some cocks present.

**Comment by Fenoxo** [comment]
Not sure if I'm too tired, but I have no idea what's being communicated here.

**Comment by Gedan** [comment]
This is how we've always done it?

If a TF changes nothing, then yeah, it's considered a failure, a dud, because *nothing actually happens*.

**Comment by ankser** [comment]
It's the only case when message displayed on following atempts of TF after successful one. Everywhere else TF skipped with no messages.
