### ISSUE TITLE
normal mode crystal goos, errors and typos - 0.6.39

### ISSUE THREAD

**Issue by Zeikfried** [OXOIndustries/Trials-in-Tainted-Space#650]
goo balls:
-All goo balls except yellow need the updated tooltip to stop the ganrael from smelling like socks.
-Updated use texts in all goo balls including yellow are still credited only to gardeford.
-line 238 (237 in yellow variant): UK spelling 'colour' is used instead of American 'color'; words "been dyed" should be omitted from tooltip as PC's hair may be that color natively

CrystalGooT1.as:
-line 53 uses feminine pronoun but the T1 is always neuter during combat
-line 185: doublespace in "its lichen cloak"
-line 198 begins a section on forcing gender modes which seems to be superfluous on the T1
-line 614: suggest revising "sending you tumbling to the ground, the ganrael swiftly landing atop you!" to "sending you tumbling to the ground with the ganrael atop you!" to eliminate sentence fragment

CrystalGooT2.as:
-line 55 uses feminine pronoun but the T2's gender varies depending on armor status

CrystalGooVersionToo.as
-classes.Items.Transformatives.GooBallYellow is not imported like the rest of the gooballs (don't know if it's relevant)
-line 269 adds a superfluous, and blank, 'Cuddlebug' button that is overwritten on line 279; unknown if this will cause any issue
-line 345: missing apostrophe and a plural pronoun is used for singular entity; suggest revising to "You give the ganrael's offer a momentary thought, but ultimately opt to leave."
-line 516: 'cosmetics' should be added to the line; I left it bracketed in case Fen wanted to inject a specific company
-line 617: errant curly brace marks the intended end of the squirter fork; move remainder of line to separate output for the shared end of paragraph
-line 715: 'flush' should be forked to 'flush' and 'flushes', for multiple vs. single vaginas
-line 789: "leave" should be "leaves"
-line 918: errant curly brace marks intended end of not-big-cum fork
-line 1029: errant curly brace marks intended end of nice guy interlude
-line 1239: nyrean 'cocks' are ingame now; suggest inserting new line for any knotted cock: "The ganrael's touch lingers on your fleshy {knot/egg-knot} a bit too long, and the bulge begins to stiffen. She releases it to extend your pleasure, or torment, further."
-line 1252: doublespace after "you could burst."
-line 1284: commenting the blurb for a color mismatch causes PC's cum to always be the color of the ganrael's skin
-line 1464 checks for absence of 'Unarmored' status on the PC instead of the enemy
-line 1590: doublespace in "it slides"
-line 1598: uses '+ enemy.skinTone +' to refer to PC's cock skin instead of [pc.skin]
-line 1606 can also exclude nyrea PCs now that nyrea TF is ingame
-line 1640 checks for the presence rather than the absence of 'Unarmored'
-line 1675: bad '+ enemy.skinTone +' call
-line 1688: time interval for the prolonged, nap-including cock loss is set the same as the very brief, no-nap unsexed loss
-line 1730: uncoded, uncommented forks for goo PCs and enemy gender

**Comment by Fenoxo** [comment]
Note: [pc.skin] should NOT be used for dicks. You'd want "[pc.cockColor] skin" for that. Or "pc.cockSkin" or something if we ever add that.
