### ISSUE TITLE
Errors initiating battles in Kara's Black Void mission

### ISSUE THREAD

**Issue by smrtone** [OXOIndustries/Trials-in-Tainted-Space#654]
Almost every time I encounter a battle during Kara's Black Void mission, it will throw the following error and skip over combat:
____________________________________________________________________________
Something bad happened!

Please report this message, and include any prior scene text or a description of what you did before seeing this message:

Version: 0.6.40

null
_____________________________________________________________________________

Afterwards, moving back into the square will restart combat, occasionally throwing the same error again.

**Comment by Fenoxo** [comment]
Could you please make a save there and pass it to us so that we can pick apart what's going on?

**Comment by smrtone** [comment]
Zipped it because github doesn't accept .sol files.

[TiTs_2.zip](https://github.com/OXOIndustries/Trials-in-Tainted-Space/files/180998/TiTs_2.zip)

**Comment by Gedan** [comment]
Tried about 5 different fights, ran into no issues.

Ensure your flash player/plugins are up to date etc.

**Comment by smrtone** [comment]
Well that was a pain and a half. I run the game offline using the standalone flash player, which was apparently running version 10.2 since Adobe apparently doesn't feel the need to update that. Eventually managed to find a download for the flash player 21 standalone player, and no more problems with fights.
