### ISSUE TITLE
Issue with Treatment not proccing correctly for herms

### ISSUE THREAD

**Issue by Aryune** [OXOIndustries/Trials-in-Tainted-Space#657]
I've tried to use the item multiple times on different saves, but it either chooses 0(girl mode) or 1(dude mode), never any of the other options. It worked in much earlier versions, but not anymore. Tried in both Chrome and IE. Credits in the save included are edited for testing purposes :)

In Items/Miscellaneous/Treatment.as it looks like if the character is a herm or neutral, it is either set to 0 or 1 not both, or any other option so it would choose either 0 or 1 and only give those results?

[Aryune - 129 days.zip](https://github.com/OXOIndustries/Trials-in-Tainted-Space/files/175993/Aryune.-.129.days.zip)

**Comment by ankser** [comment]
includes/nawTexas/treatment.as (treatment TF implementation) contains only two paths, any other mode isn't realized. If you can describe yourself any special path like amazon - it's in your hands.

**Comment by Aryune** [comment]
But it worked before? The first time I used it on my character early in development it had both 0 and 1 modes happen, as is stated in game text and in the code comments. 

I could write up a third path for this to happen, whereas it's literally merging both 0 and 1 into a new mode (2) if you wanted?

**Comment by ankser** [comment]
As I can see (sorry for possible mistake, haven't experience with git), it was removed more than year ago if present at all - don't want to dig manually under 2nd file renaming at Dec.2014.

**Comment by Fenoxo** [comment]
I'm pretty sure it could never do both at once. You've got to wait for
proper herm options.
