### ISSUE TITLE
.40 Aina bug

### ISSUE THREAD

**Issue by Feralcus** [OXOIndustries/Trials-in-Tainted-Space#658]
Kinda iffy, but my character has visited that party planet "Poe-A" and acquired the centaur suit thing (of admittedly dubious nature) and this line does seem off in relation to that.

""There’s no way you can eat as many as she put out. As a centaur, she has quite the appetite!""

**Comment by Fenoxo** [comment]
Fixt via 053a8fd79399637423bc0d878cde7f1f46a2ef9e
