### ISSUE TITLE
.40 tarkus typo

### ISSUE THREAD

**Issue by Feralcus** [OXOIndustries/Trials-in-Tainted-Space#659]
Exhibition jerk it, centaur pc.
Missing space here.

"That naughty little thought pushes you right over the edge. With a sharp, high-pitched cry, you shiver and shoot your white spunk all over the ground and squirt your girl-lube from your horse->>>>cuntutterly<<<< cream yourself."

**Comment by Fenoxo** [comment]
Fixt via b8b5b5b05b8405adbf122d157b43392d421c1ff9
