### ISSUE TITLE
Error #1069

### ISSUE THREAD

**Issue by AnAnonOnline** [OXOIndustries/Trials-in-Tainted-Space#699]
Version: 0.6.45

ReferenceError: Error #1069
	at classes.Resources::NPCBustImages$/getBounds()
	at classes.UIComponents.SideBarComponents::SingleCharacterDisplay/setBust()
	at classes.UIComponents.SideBarComponents::SingleCharacterDisplay/UpdateFromCharacter()
	at classes.UIComponents.SideBarComponents::PlayerPartyBlock/showForCreatures()
	at classes.UIComponents::RightSideBar/showPlayerParty()
	at classes::GUI/showPlayerParty()
	at classes.GameData::CombatContainer/showCombatUI()
	at classes.GameData::CombatContainer/showCombatMenu()
	at classes.GameData::CombatContainer/beginCombat()
	at classes.GameData::CombatManager$/beginCombat()
	at classes::TiTS/startPhoenixPirateFight()
	at classes::TiTS/buttonClick()

**Got above text when engaging the Void Pirates during the fight onboard the Phoenix (after clicking next from the scene when you enter the cargo hold and the walkway collapses). Had status effects Mare Musk and Heart Tea at the time, if that's relevant. Clicking through it a few times loads the people into group combat one by one, idk if this is known or whatever cos I'm playing on the public build, but still thought it'd be better to mention it. Text of the previous scene below:**

“Okay, we’re in. Atmosphere and pressure restoring in the damaged sections as we speak. I’m showing several life-signs in the cargo bay: it looks like they drilled in via assault pod. Captain en Illya’s still alive, I think. Be ready for a fight.”

You nod, and kick open the cargo bay door. You find yourself overlooking the bay proper, walking out into a catwalk over the bay, two stairs leading downwards along the sides. Below, you can see several men in black, skintight spacesuits taking cover behind crates and barrels, trading gunfire with a lone figure sitting in a pool of her own blood, firing a heavy-looking Hammer pistol one-handed as she clutches her side. 

“Saendra!” the A.I. gasps, seeing what you assume to be the captain badly wounded. “Quick, we have to help her!”

Doesn’t look like you have a choice. Her sudden outburst has drawn the attention of the pirates, who look up in shock to see you, leveling their weapons upward. Uh-oh. 

You dive into cover just in time as a volley of automatic weapons fire pummels into the catwalk, chewing through the thin metal until it looks like Swiss cheese. Unfortunately for you, the catwalk buckles under the hail of lead, and you have just enough time to scream before you go plummeting to the deck, smashing into the ground. Conveniently, you land in cover behind some chest-high crates.

“Who the hell is that?” one of the pirates shouts, slamming a new magazine into a machine-pistol.

“I don’t fucking know! Just shoot ‘em!”You perch behind cover wherever you can find it, ready to return fire side-by-side with your companion.

Saendra lithely snakes out of cover from time to time, taking potshots at anything and everything she can sight quickly enough before ducking back to safety.

A gang of unruly, vicious-looking space toughs, these Black Void pirates are armed to the teeth with machine-pistols, rifles, shotguns, and everything in between. Ausar, humans, kaithrit girls, and even a Centaurin packing a gatling-laser make up their ranks. They’re all wearing skintight black space suits and peppering the cover around you with bullets.

**Comment by Jacques00** [comment]
It seems the new bust handling must have screwed up the party combat bust displays.

**Comment by Gedan** [comment]
Fixed.
