### ISSUE TITLE
How do I use the save editor in a desktop?

### ISSUE THREAD

**Issue by 7Se7eN7** [OXOIndustries/Trials-in-Tainted-Space#706]
I have no idea how to utilize these files.

**Comment by Krynh** [comment]
Visit the forums there's a handy guide to save editing. https://fenoxo.com/forum/index.php?/topic/1359-bestest-minerva-guide-to-save-editing-ever/

**Comment by dragontamer8740** [comment]
The 'official' editor appears to have been abandoned, unfortunately. But minerva works.

**Comment by Anonymous-BCFED** [comment]
I'm working on a standalone save editor, and one of the changes "mingling" with #972 is a fixed TiTSSE.

**Comment by dragontamer8740** [comment]
@Anonymous-BCFED This isn't that .NET one that uses WPF and therefore won't even run in mono, right?

**Comment by Anonymous-BCFED** [comment]
@dragontamer8740 The logic and data storage is decoupled, but yes, that one.

I should mention that #972 also enables TiTSSE to edit perks.

**Comment by dragontamer8740** [comment]
@Anonymous-BCFED Alright. I still can't use it at all without setting up and learning C# and rewriting an entire UI, but noted.

Why not winforms or GTKSharp, though?
