### ISSUE TITLE
Crash in Kara quest 2

### ISSUE THREAD

**Issue by weee123** [OXOIndustries/Trials-in-Tainted-Space#726]
in the third room after repling down there is a crash in NPCBustImages.as in line 173.  I am attaching a screenshot of the code in question and the information from FlashProffesional.  The crash happened when I clicked the next button.
![image](https://cloud.githubusercontent.com/assets/10012638/14683547/4a3ea350-06f9-11e6-9a35-dbe250340dab.png)
The information from flash proffesional
![image](https://cloud.githubusercontent.com/assets/10012638/14683564/643328ee-06f9-11e6-97d6-7544787abe1d.png)

**Comment by Gedan** [comment]
You're playing an old version; it's already been fixed.

https://github.com/OXOIndustries/Trials-in-Tainted-Space/blame/master/classes/Resources/NPCBustImages.as#L173
