### ISSUE TITLE
Jade's Sex Menu is broken

### ISSUE THREAD

**Issue by eldestdawn** [OXOIndustries/Trials-in-Tainted-Space#759]
Doesn't matter which option you select, it always comes back to the sex options with no way to back out or do anything else.

**Comment by eldestdawn** [comment]
as a side note, i gave her nipples before the latest patch and have the full sex options. just in case that's part of what's breaking her menu.

**Comment by Jacques00** [comment]
This is most likely related to the typo in the orgasm function that is affecting females (PC and NPC). This has been fixed in a previous commit.
