### ISSUE TITLE
Zaalt 'Assist Him' Uveto Intro

### ISSUE THREAD

**Issue by blkdrgn216** [OXOIndustries/Trials-in-Tainted-Space#765]
![image](https://cloud.githubusercontent.com/assets/19255050/15100259/e8560a34-153a-11e6-81a0-a06557279d9b.png)
According to the Github code, there are supposed to be three options but in game there is only one. Was it meant to be that way or did something go wrong?

**Comment by Jacques00** [comment]
Fixed in #760.
