### ISSUE TITLE
Grenade item issues in group fights

### ISSUE THREAD

**Issue by Trogdor-the-Burninator** [OXOIndustries/Trials-in-Tainted-Space#770]
I decided to give myself a few flashbangs using minerva for funsies, and also because blowing up a planet to get access to a grenade is dum. I don't see why that should make them not work correctly, but I figured I'd mention it just in case.
I've noticed a couple of issues when I've tried to use them in group fights, and then in the course of testing them, I noticed issue 2) also affects EMP grenades.
1) When you use flashbangs.. well, I don't know how the Smuggler skill works, but for the item, it asks you to pick a target, and it only blinds that target. This is counterintuitive, as whenever an enemy throws a flashbang during a group fight when you have an ally, the flashbang tries to blind **both you and your ally**. ( https://github.com/OXOIndustries/Trials-in-Tainted-Space/blob/master/classes/Characters/SX1GroupPirates.as, https://github.com/OXOIndustries/Trials-in-Tainted-Space/blob/master/classes/Characters/KQ2BlackVoidGrunt.as  ) Shouldn't flashbangs work the same no matter who's throwing it? Or are we going on the assumption that the black void have access to much better flashbangs than you do? :Q
2) I noticed when I was using Flashbangs during the Fazian quest warehouse fight that I was only able to throw them at Red Myr C. I couldn't throw them at the other two guards, or Ehstraffe. I seem to remember this also being the case when I tried to use it during other group fights (Deck 92); I could only throw it at the last enemy. Then I tried it again after I KO'd Red Myr C; I was now only able to throw it at B. After KO'ing B, I can now only throw at A, and so on. Then I tried EMP grenades and found that they worked the same way.

**Comment by Gedan** [comment]
Fixed/tweaked/didstuff™
