### ISSUE TITLE
Bust issue

### ISSUE THREAD

**Issue by Tdrago** [OXOIndustries/Trials-in-Tainted-Space#774]
Busts are kinda all over the place in-game right now. I swapped primary to Cheshire for the naleen busts, and it still uses a different bust (looks like Gats' work, but it isn't on wiki to compare). In fact, I've seen a lot of different busts to the art styles I expect. Did something get mixed up in the bust code or is it just my comp that's screwing up?

**Comment by Fenoxo** [comment]
Did you remember to hit the "save" button after making your bust selection? It works fine for me.

**Comment by Tdrago** [comment]
Ok, closing and restarting worked. Just saving didn't though, weird. I'll just chalk it up to a glitch in my comp I guess.
