### ISSUE TITLE
[6.55] Nyrean Alpha Huntress bad end second scene aborts silently

### ISSUE THREAD

**Issue by NeitherMeNorYou** [OXOIndustries/Trials-in-Tainted-Space#796]
The Nyrean Alpha's second bad end scene progresses until the PC is told to get on all fours, then simply aborts silently without doing anything else. In this case my PC has Nyrean Eggs both in the butt, as well as the vagina.

The pregnancies in both cases are nyrean eggs, with the first pregnancy being the butt-eggs from the ride cock victory scene, and the second pregnancy from the first bad end scene of the Nyrean Alpha Huntress.

The scene will play properly once at least one of those pregnancies comes to term, but until then the scene can be repeated to break like this over and over.

-----------------
### Quote of the entire scene:

The Alpha nimbly pirouettes behind you, slapping your impressively tweaked Salamander Rifle to the ground with the haft of her spear as she does so. A moment later and her voluptuous breasts are pushed up against your back, her spear discarded in favor of seizing your spacious ass. She breathes hotly on your neck before sweeping your feet out from under you, sending you tumbling to your hands and knees. You hear a gentle laugh from behind you.

“A fitting position for you, offworlder. Crawling on your hands and knees before me.”

You turn to be greeted by the sight of her disrobing, her chainmail bikini slinking down her buxom form as her pseudo-cock engorges to its full length. You watch transfixed, the gentle side to side swaying hypnotizing you until she rests her hardness right on your face. Your mouth hangs open slightly in awed subservience before you remember you’re not here to be this alien’s slave... right? You look up at her and she grins viciously as you meet her gaze.

“Oh, offworlder. So naive. After making such a show of being my slut, you’re going to offer resistance now? After I - ” she leans in, taking your face in her hands and lowering her voice to a sultry whisper, “dominated you so thoroughly and left you needing more?”

She stands back up, taking no notice of the precum now smeared across your face or your goo-cock rapidly stiffening in your premium Armstrong suit}at her sensual words and the memories you share of her fucking you over and over.

“Is that not why you’re here, offworlder? To bequeath your body to me as a fertile breeding ground? I can’t imagine what other business you have down here that makes you so persistent.” She says innocently before fixing you with a smile.

She’s mocking you. She’s mocking you but to your shame you’re only getting hornier, your face red and your breathing heavy as she puts her cock back on your face and waits. You can’t take it.

“Just... do it.” You mutter, defeated.

“Do what?” She beams at you, clearly enjoying your emotional conflict.

“Just f-fuck me.”

“Oh,” she says, her smile growing wider, “but I’m not waiting for your permission. I’m waiting for you to be honest with yourself.”

Whatever. You tell yourself she’s clearly not going to make the first move and you don’t want to sit here forever, so it’s okay if you open your mouth and slurp up the precum that’s been dribbling down the underside of her thick cock. Motivated by her approving moan, you raise your hands to hold her length. You reverently rub up and down her pseudo-cock, taking care not to catch your fingers on the barbs you’re so intimately familiar with. Now that you have her gigantic tool in front of you again, it’s hard to believe it ever fit in you.

“Gooood girl. Now open up, you need to get me ready.” She chides you gently.

You automatically spread your fuck-pillows as far as they’ll go at her instruction and the Alpha eagerly thrusts into you, not hesitating to plunge her cock right down your throat and make use of her willing slut. Gagging isn’t even a possibility with your neck so thoroughly filled with her, but you unconsciously shift your head anyway to ease her passage into your depths. She makes a low, satisfied groan as she slips further into you and holds your head close, standing still as she revels in the warmth of your throat. You can scarcely breathe, but stay still holding her cock in you secure in the knowledge she won’t let serious harm come to you. A few moments pass before she releases you with a dainty sigh, the barbed head of her cock softly scratching the inside of your throat as it comes back up. You let her out with a wet ‘ogh’ and let your head hang for a bit, panting tiredly as you get your breath back.

She circles around you in predatory fashion, leaving little doubt as to what her intentions are once she’s behind you. She doesn’t give you long to savor your anticipation, slapping your heavy, cushiony backside and eliciting a gasping moan from your oral fuck-cushions when her hand stays there, squeezing possessively.

“Down, starwalker. Present yourself.”

--------------------
All that can be done after this is to click next to leave combat.

**Comment by Gedan** [comment]
I had a quick mess about with this; I'm pretty sure I did find an issue in vaugely the same place but I think the "scene ends abruptly" part has been fixed at some point in the past as I can't get it to happen.
