### ISSUE TITLE
Where locate text string "shields"?

### ISSUE THREAD

**Issue by Sscoy** [OXOIndustries/Trials-in-Tainted-Space#798]
Where can I find the text string "SHIELDS" for PC's combat stats? I edit it in Creature.as, BigStatBlock.as, CompressedStatBars.as, EnemyEncounterBlock.as, SingleCharacterDisplay.as, but nothing has changed.

**Comment by Jacques00** [comment]
It should be "shieldDisplayName" in Creature.as--but if you alter it and load a save file with PC already created, it might not register as what you want, so you'll probably have to make a function define it for you, if I'm not mistaken.

**Comment by Sscoy** [comment]
Thanks. For a new character it works.
