### ISSUE TITLE
Bess sex scenes still using old cock volume checks

### ISSUE THREAD

**Issue by Garzhad** [OXOIndustries/Trials-in-Tainted-Space#810]
While you may have addressed Bess having ridiculously girthy cocks by setting the cthickness to reasonable values, her sex scenes for the saurian cock and perhaps even others still use the pc.cuntThatFits variable that is set to the cock volume of the old, watermelon-thick cock. The current volume of 1360 is, according to my calculations, over 6 times what the cock should be; 20"L with cThickness of 1.2(4") would be a cock volume of approx. 218 using the formula I got from the game files.
In bess.as:
10716: if (bess.cocks[0].cType == GLOBAL.TYPE_SAURIAN)
10717: {
10718: if ((pc.hasVagina() && pc.cuntThatFits(1360) >= 0) || pc.analCapacity() >= 1360) addButton(2, "GetDoggy", bessGetDoggy, undefined, "Get Doggystyle", "Take it from [bess.name], doggy style! [bess.HeShe] must have a cock.");
10719: else addDisabledButton(2, "GetDoggy", "Get Doggystyle", "Take it from [bess.name], doggy style! [bess.HeShe] must have a cock that [bess.heShe] can squeeze into you!");

11566: public function bessGetDoggy():void
11567: {
11568: // Cunt that fits Saurian-type cocks, ass doesn't fit
11569: if (pc.hasVagina() && bess.cocks[0].cType == GLOBAL.TYPE_SAURIAN && pc.cuntThatFits(1360) >= 0 && pc.analCapacity() < 1360)
11570: {
11571: bessGetDoggySelected(true);
11572: return;
11573: }
11574:
11575: // Cunt doesn't fit Saurian-type cocks, or no cunt
11576: if ((pc.hasVagina() && bess.cocks[0].cType == GLOBAL.TYPE_SAURIAN && pc.cuntThatFits(1360) == -1) || !pc.hasVagina())
11577: {
11578: bessGetDoggySelected(false);
11579: return;
11580: }
11581:

12617: if (bess.hasCock())
12618: {
12619: // If you've equipped Bess with the saurian / dino-dick, the pc's orifice capacity must be able to take a 20 inch long, 12 inch wide cock.
12620: if (bess.cocks[0].cType == GLOBAL.TYPE_SAURIAN)
12621: {
12622: if ((pc.hasVagina() && pc.cuntThatFits(1360) >= 0) || pc.analCapacity() >= 1360) addButton(2, "Missionary", bessIntimateGetDoggy, false, "Get Intimate Missionary", "Take it from [bess.name], missionary style.");
12623: else addDisabledButton(1, "Missionary", "Get Intimate Missionary", "Take it from [bess.name], missionary style. [bess.HeShe] must have a cock that [bess.heShe] can squeeze into you!");
12624: }
12625: else
?
12753: bessHeader();
12754:
12755: var vagIdx:int = -1;
12756: var cVolume:Number = -1;
12757:
12758: if (bess.cocks[0].cType == GLOBAL.TYPE_SAURIAN)
12759: {
12760: vagIdx = pc.cuntThatFits(1360);
12761: cVolume = 1360;
12762: }
12763: else if (pc.hasVagina())

**Comment by Fenoxo** [comment]
The number should really just be replaced with bess.cockVolume(0).
