### ISSUE TITLE
Thermal undies don't offer Freezing protection

### ISSUE THREAD

**Issue by Garzhad** [OXOIndustries/Trials-in-Tainted-Space#811]
Yes, I know Freezing is a new thing and you probably just forgot about this, but the Thermal undies still only offer burning protection whereas the tooltip hints it should offer Freeze protection as well for the new Uveto area.
Perhaps the Furry Bra should have some freezing protection as well?

**Comment by Fenoxo** [comment]
I'd think you'd need something a bit more potent than thermal undies to
survive Uveto.

**Comment by Jacques00** [comment]
Yea, that's true--but a tiny bit of freezing resistance might help in conjunction with other clothing combinations. The wilds of Uveto will definitely need something warmer to survive.
