### ISSUE TITLE
Error #1009 - Sexy times with Yarasta

### ISSUE THREAD

**Issue by faustine92** [OXOIndustries/Trials-in-Tainted-Space#814]
See below! Probably tail-cock related?

-F

---

You eagerly strip down and secrete your parasitic tail-cock, erect and ready to impregnate. Yarasta watches your pseudo-male organ fill, transfixed and fumbling the fasteners on her clothes.

“I’m definitely getting a piece of that,” says the myr confidently. She finishes with the last button and throws open her blouse, revealing cute, small breasts that are just barely darker than her skin. Oddly, she has very little chitin - though her jointed ‘gloves’ do go all the way up to cover her shoulders and collarbone, connecting in a shape like a mantlet. Yarasta follows your eyes and closes her shirt playfully. “Don’t stare; it’s rude,” she admonishes with a smile, then finishes undressing, dropping her blouse and sliding the skirt over her head.

“So how do you want it?” you ask.

The myr reaches out a hand to touch the tip of your dick, then quickly draws back with a shiver. She turns around and kneels down, then moves onto all fours. “Like this,” she says, two lower hands reaching back to spread her vagina and voice dripping with lust.

You slide your tool into the perverted, honey-coated hole, imploringly held open by Yarasta’s fingers. The myr shivers and rolls her eyes as you enter, and her hands fall away, planting on the floor beside the other two to stabilize the giddy girl. Her slippery, deep abdomen beckons you further and further in until at last you have no more prick to give. “That’s good,” she buzzes.

With gusto, you start to drive into the bookish myr, who shifts and wiggles right back to ensure that your sensitive cock-flesh is always wrapped deep in her folds. “More,” she mumbles, then louder: “More!”

You stick it to her, rocking her with the momentum of your plunges. Yarasta grunts and sweats like an animal as the pace picks up, occasionally looking back over her shoulder with a mixture of worry and adoration. Her vagina drools sticky honey-like lube on your alien cock, down to the sensitive slit that conceals it. The myr’s arms become increasingly wobbly as your pounding gets to her, lowering her posture until she looks more like a beast in heat than an educated woman.

The alien organ in her abdomen ripples and convulses around 

Something bad happened!

Please report this message, and include any prior scene text or a description of what you did before seeing this message:

Version: 0.6.58

TypeError: Error #1009
	at classes::Creature/cockShape()
	at classes::Creature/cockNoun2()
	at classes::Creature/tailCockDescript()
	at classes::Creature/getDescription()
	at classes.Parser::ParseEngine/convertSingleArg()
	at classes.Parser::ParseEngine/parseNonIfStatement()
	at classes.Parser::ParseEngine/recParser()
	at classes.Parser::ParseEngine/recursiveParser()
	at classes::TiTS/doParse()
	at classes::TiTS/output()
	at classes::TiTS/doYarastaDoggieStyle()
	at classes::TiTS/yarastaPicksSexSceneRouter()
	at classes::GUI/PressButton()
	at classes::TiTS/pressButton()
	at Function/()
	at classes::BoundControlMethod/ExecFunc()
	at classes::InputManager/ExecuteKeyCode()
	at classes::InputManager/KeyHandler()

---

Appearance:

You are a human. You’re a good 5 feet and 10 inches tall by ancient imperial measurements and 1.78 meters in the more accepted metric system. Right now, you’re wearing a suit of armor constructed from an active gray goo, going commando down south, and letting your torso breathe, unrestricted by any undertop.

Your suit of armor is silvery-gray. The outfit itself is completely closed, much like a body suit should be.

Your face is human in shape and structure, with pale skin. Overall, your visage has a beautiful, feminine shapeliness that’s sure to draw attention and full lips. Regular blue eyes allow you to take in your surroundings without trouble. Your long, iridescent hair looks good on you, accentuating your features well. Your mouth contains a tongue.

You have a humanoid upper body with the usual torso, arms, hands, and fingers. You have noticeable thighs that draw the attention of those around you, and your compact ass looks great under your gear. A writhing, sinuous appendage flows after you, bobbing and undulating with the slightest movement of your hips. Most of the length of the thing is coated in pale skin, culminating in a proud purple head that’s distinctly cock-shaped in nature. Two normal human legs extend below your waist, ending in normal human feet. Your flat belly is nice and smooth.

You have two pillowy breasts, capped with one 0.4-inch pronounced bud each. The coin-sized areolae are pink. You could easily fill a big DD-cup bra.

Your sexual equipment is located at your humanoid waist. You have a pink, human vagina, with one 0.5-inch clit. Thin streams of slime occasionally dribble from your well-practiced, pink slit, its lips slightly parted.

You have one tight backdoor, placed between your cheeks where it belongs.

Since some parts of you are made of goo, you can adjust them if need be.

Teal wiggles around your body, making you aware of her presence.

**Comment by Jacques00** [comment]
You character doesn't have a penis (besides the cock tail), right?

Hopefully fixed with the recent commit of #807 . Had to make some adjustments to cockShape() so it doesn't derp with non-existing cocks.

**Comment by Fenoxo** [comment]
I mighta gone ahead and tweaked it in a different way.

**Comment by Fenoxo** [comment]
Gonna close this since we haven't heard about any more problems (or gotten any responses).
