### ISSUE TITLE
Possible bug with lustcoefficient for CumQ equation?

### ISSUE THREAD

**Issue by Garzhad** [OXOIndustries/Trials-in-Tainted-Space#817]
I'm not sure if this is really a bug or not, or if it was just done before the max lust increases from dumbfuck/treatment were a thing and never changed. But I had the lustcoefficient figured to be a lust percentage-based alteration to cum amount, when really it goes off your current total lust.
The equation in creature.as: 

7604:		//lust - 50% = normal output. 0 = 75%. 100 = +125% output.
7605:		var lustCoefficient: Number = ((lust() / 2) + 75) / 100;
7606:		quantity = cumMultiplier() * lustCoefficient * maxCum() / ballEfficiency;

Going by the comment being at max lust(normally 100) increase cumamount by 25%, and being at 0 reduces it to 75%. But the equation is based off current lust amount, not a percentage of maximum lust, so the 30 maxlust increase from Dumbfuck and 40 increase from the treatment considerably increase the output bonus, to a maximum bonus of +60% at 170lust

**Comment by Fenoxo** [comment]
This is intentional.
