### ISSUE TITLE
A complaint about the Nyrea transformation

### ISSUE THREAD

**Issue by mcgmcg** [OXOIndustries/Trials-in-Tainted-Space#843]
After becoming a full-blown Nyrea (boy-pussy and all), Nyrean huntresses still claim that you're depriving them of their pressure sperm when they fuck you, despite having the correct biology to not be a deceitful off-worlder. 

Re-writing every scene to account for a swap in biology is understandable, but it seems neglectful not to mention it in at least Nyrean scenes.

**Comment by Fenoxo** [comment]
This is why Nyrea TF was a mistaaaaaaaaake
