### ISSUE TITLE
6.64 TiTs  .. .. ..Crashed?

### ISSUE THREAD

**Issue by Feralcus** [OXOIndustries/Trials-in-Tainted-Space#855]
So I was playing just fine for a good while and everything was fine, but just now when I tried to save it didn't work. I could get to the save menu, but when I tried to select a save to overwrite it gave me the "Do you want to overwrite" message and I couldn't get past it. I hit the yes button and just nothing happened. It still let me hit no which took me back to the save menu but even when I chose an empty save it just didn't do anything at all. (Although I think the comments box at the top may have disappeared when I did that)

Trying to save to file brought up the saving to file dialogue but never brought up the window. 

Closing and reopening seems to have fixed everything, saving works again and all that....

**Comment by Fenoxo** [comment]
Sounds like a local problem with your flash player accessing its storage.
