### ISSUE TITLE
[0.6.67] Hana flirt scene crash

### ISSUE THREAD

**Issue by DevilAffect** [OXOIndustries/Trials-in-Tainted-Space#866]
After selecting flirt and then backroom this pops up: 

“Hey.” You begin, lamely, leaning against the bar. “I can’t help but notice it looked like you enjoyed yourself before, when I was out of it...”

You catch Hana by surprise, her mug-cleaning hand going still as an eyebrow perks upwards, questionably.

“It’s just, you know. Neither of us got off... and that doesn’t seem like much of a returned favor to me, you know?” Rapping your fingers along the bartop, you trail off and simply smile. A smile that, quite quickly, gets mirrored by the prickly barkeep.

“All right.” Hana didn’t have to think it over very long, setting her glass and rag down to, instead, lean forward much like you are. Rather close, now!

“And just what do you have in mind, traveler? I’ll be rather cross if it doesn’t involve returning the favor.” Awh yeah, looks like this is happening.

Something bad happened!

Please report this message, and include any prior scene text or a description of what you did before seeing this message:

Version: 0.6.67

ArgumentError: Error #1063
	at classes::TiTS/buttonClick()

**Comment by abdicatedbear** [comment]
A lot of freezer.as seems to have that issue - the calls to addButton() are in the wrong argument order.
