### ISSUE TITLE
Flower for Lys

### ISSUE THREAD

**Issue by eldestdawn** [OXOIndustries/Trials-in-Tainted-Space#888]
After giving a flower to Lys (gold ant deserter) the Tail Cock option gives the regular cock scene.

**Comment by Jacques00** [comment]
The scene should be the same, but using descriptions for the tail cock rather than the pelvis cock (if any).

**Comment by eldestdawn** [comment]
seems kinda pointless to just have the cock description different and 2 buttons...

**Comment by Jacques00** [comment]
If the character has both, they can choose either one--the scene will adjust itself based on which cock is chosen.
