### ISSUE TITLE
Anno in two places

### ISSUE THREAD

**Issue by eldestdawn** [OXOIndustries/Trials-in-Tainted-Space#890]
When you visit bars to talk to Anno, her button is in the same slot as Kiro's. Because of this, the button in Anon's Bar to meet Kaede can be present at the same time as Anno's talk scene. This also makes it difficult to meet Kiro sometimes since they share button space.

**Comment by Wishbringer** [comment]
Save in the bar, then load, you'll get different buttons every time.
I've seen one case where the Anno button was displayed twice though (not sure in which pub that was).

**Comment by Fenoxo** [comment]
Kiro & Anno use the random NPC bar scene system I added for Kiro.

We need to make sure Anno can't be met in the bar when their are fixed events that involve her proccing, however I need text from said events to track them all down in the code (that or to spend an hour or two paging through her content myself)

**Comment by Fenoxo** [comment]
JCup claims to have fixed this: https://github.com/OXOIndustries/Trials-in-Tainted-Space/pull/887/commits/6eed1efea3a56746018921d5d880f7bc01a1b5e7
