### ISSUE TITLE
Temporary gear appearance…

### ISSUE THREAD

**Issue by Otaku-chan** [OXOIndustries/Trials-in-Tainted-Space#912]
—- Some Time Later —-

When you finally leave Big T’s office, you’re barely able to put one foot in front of the other without tripping. You hold your gear to your cum covered melons. You’re in a complete daze as you stumble giddily past his receptionist, half naked and too spaced out to care.

As you leave, you barely register the governor buzzing Zephyr on the intercom, and the rough, breathless voice that follows. “... Cancel my next few appointments, Zephyr. This bull’s all worn out!”

------------------------------------------------------------------------------------------------------
1. I was naked when I went in to see Big T.
2. I had no items in my inventory when I went in to see Big T, except 'BBQ to go' which I don't count as gear.
3. I had no equipment on when I went to see Big T.

Why do I suddenly have (at least some) clothes on?
What gear am I holding against my breasts?

I only have the BBQ when I check my stuff, and am still naked, after the event, so nothing was added,
And if cum counts clothes, I was completely clothed with how much come has built up on my body.

Not sure if you care about this event's consistency to the Player's inventory, status, and equipped gear, but I thought I should mention it, in case you feel it should have said consistency.

**Comment by Jacques00** [comment]
This should fix the naked issue, but the gear issue is not an issue because it is always assumed that Steele carries around "gear", be it a utility belt, backpack, purse, pouches, etc. Even if the character doesn't carry any particular items.
