### ISSUE TITLE
Chrome's new save system

### ISSUE THREAD

**Issue by eldestdawn** [OXOIndustries/Trials-in-Tainted-Space#913]
Almost had a panic attack when i went to load a save and saw that there were none to load even though i was playing earlier today. looked in the usual place for the save files and they were still there and i found it odd that i couldn't load. long story short google has a different place for your saves depending how you are playing. localhost and #localWithNnet. if you go to load your save and find there are none, copy your saves from localhost to #localWithNet and try again.

**Comment by Fenoxo** [comment]
This isn't a bug with our game.
