### ISSUE TITLE
Shop Tooltips have Incorrect Prices

### ISSUE THREAD

**Issue by Fenoxo** [OXOIndustries/Trials-in-Tainted-Space#926]
Was working on Kirila's shop - noticed the shop display showed the weapons costing approx 19,000 while the tooptips were reporting over 20,000. On purchase, the first (and therefore correct) price was charged.

**Looks like the issue relates to the smuggler perk discount. So probably not a high priority.**

**Comment by eldestdawn** [comment]
I think it's better that the tool tip displays the regular price while the shop displays what you actually pay for smugglers so you know you are actually getting the discount/markup.
