### ISSUE TITLE
Reflex and Aim

### ISSUE THREAD

**Issue by eldestdawn** [OXOIndustries/Trials-in-Tainted-Space#929]
Reflex and aim stats are showing the wrong value. I checked with the save editor and it shows they are maxed out but in game it shows they are 5 points lower.

**Comment by Jacques00** [comment]
Does your character have any status effects or equipment that might modify those stats?

**Comment by eldestdawn** [comment]
i took everything off, am not pregnant, and have no other status effects active. the value is still wrong. when i leveled up, i put points into aim and reflex and instead of giving me max value, it dropped down to 5 below max.

**Comment by Jacques00** [comment]
Well, the 5-below issue is probably due to an aimMod/reflexMod value that didn't clear properly or are still active. Effects that alter these values are usually one of the drink/drunk status effects, Lane hypnosis effects, or mimbranes. Some combat effects also change these values, but they should only be during combat and the values are reset after combat finishes.

**Comment by eldestdawn** [comment]
yeah but i don't have any active status effects, pregnancies, or anything else that is dropping the values.

**Comment by eldestdawn** [comment]
would a hungry cunt snake cause the drop and make it permanent if the snake is removed before satisfying it?

**Comment by Jacques00** [comment]
I don't think a hungry cunt snake would affect stats at all (though I could be wrong).

It might be possible that your character could have gotten the "Gassed" status effect in combat (with Shade or Zaalt), then after combat, the aimMod and reflexMod values didn't add back in when the effect was cleared. If so, it might have been an issue from an old version of the game as the version now should add and remove values properly.

**Comment by eldestdawn** [comment]
Might want to check the Zaalt combat flags again. I fought him on the new version and looking back, that's about when i started noticing my stats were lowered. I didn't have them maxed out yet but didn't think anything of it at the time either.

**Comment by eldestdawn** [comment]
also, off topic, the ship is surprisingly sturdy on the inside. tossed a few grenades at the guy and no damage to the ship interior followed.

**Comment by Jacques00** [comment]
Regardless if they are maxed out or not, your character's Codex > Stats > Other page should show what Mod values are affected on your character. Try checking them before and after the event to see if they have changed.

**Comment by eldestdawn** [comment]
i'm gonna have to write this off as a bugged save. i can't replicate the issue and don't know how to go about fixing it.
