### ISSUE TITLE
Dong Designer Malfunction

### ISSUE THREAD

**Issue by eldestdawn** [OXOIndustries/Trials-in-Tainted-Space#941]
Penis size was increased from 13 to 36 using throbb and was able to use the dong designer enough times to split it into multiple penises. After splitting it, penis size is now 26 inches and unable to use the machine.

**Comment by Jacques00** [comment]
For multiple penises, it seems that the user cannot insert penises that are too big. For single-penis characters, it may work at any size. Not sure if intentional however (for accessibility reasons), or just an edit left uncorrected after testing.

**Comment by eldestdawn** [comment]
I think it was supposed to be changed after testing but they missed a line of code. Also, the volume of the 2 penises are about the same as the single that was split so it should still work with the machine.
