### ISSUE TITLE
More Inessa fixes and changes

### ISSUE THREAD

**Issue by SenKanashimi** [OXOIndustries/Trials-in-Tainted-Space#942]
Another round of minor fixes and changes
Added more context to why she packs up shop so quickly
Added a small chat with Xanthe that explains how the PC gets the collar rather than just having it appear
Tweaked the wording to make it match that Xanthe gave the PC the collar
https://docs.google.com/document/d/1oIQeMHl_ca0NGfvwmzkUo1PY0q9OZX8gSb5ifOeN18s/edit?usp=sharing

**Comment by Fenoxo** [comment]
Handled.
