### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by Tdrago** [OXOIndustries/Trials-in-Tainted-Space#969]
I've only seen this in the latest update, but whenever I try to load a save file while in combat (to get specific weapons or skip a loss scene that I've seen already, possibly several times if I'm under-leveled for the area), the game freezes, forcing me to close and restart the game. I'd have attributed this to a lag in connection, since it isn't the best, but it also happens on my tablet (which cannot get the  online version and must be downloaded). Any idea what might be happening?

**Comment by Jacques00** [comment]
That's strange, I seem to be getting this bug as well.

The actual error is:
> Error: Error #1502: A script has executed for longer than the default timeout period of 15 seconds.
> 	at classes.DataManager.Serialization::UnversionedSaveable/getSaveObject()[C:\...\classes\DataManager\Serialization\UnversionedSaveable.as:42]
> 	at classes.DataManager.Serialization::VersionedSaveable/getSaveObject()[C:\...\classes\DataManager\Serialization\VersionedSaveable.as:77]
> 	at classes.DataManager.Serialization::VersionedSaveable/getSaveObject()[C:\...\classes\DataManager\Serialization\VersionedSaveable.as:61]
> 	at classes.DataManager.Serialization::VersionedSaveable/getSaveObject()[C:\...\classes\DataManager\Serialization\VersionedSaveable.as:61]
> 	at classes.DataManager.Serialization::VersionedSaveable/getSaveObject()[C:\...\classes\DataManager\Serialization\VersionedSaveable.as:61]
> 	.....

**Comment by Jacques00** [comment]
Fixed with #371
