### ISSUE TITLE
Kiro Canada loop

### ISSUE THREAD

**Issue by eldestdawn** [OXOIndustries/Trials-in-Tainted-Space#978]
After going through a bunch of the content for her, when you choose She's Hot (after talking to her sister and then talking to Kiro, it is one of the options) and then going all the way to the point of to join her in the shower or decline, if you choose no it gives you a few lines with the yes or no options again and your only option is to go yes. 

This is what 'No' option had for me.

You slink out of the ship and back to your own, trailing Kiro’s cum behind you as you go. Everyone you pass can see and smell what she did to you. The 

It cuts off there but can get out of the loop by clicking yes.

**Comment by Jacques00** [comment]
I'm pretty sure I fixed this bug in the pull request #976 already--so once that gets merged, it should fix the issue. It was a typo that needed "indexOf", I think.
