### ISSUE TITLE
Nuki nuts perk not working properly?

### ISSUE THREAD

**Issue by MillaSteele** [OXOIndustries/Trials-in-Tainted-Space#989]
I noticed that when resting the status doesnt update with any of the nuki nuts Endowed messages since build 0.6.88 (the last build i was on) on builds 0.6.90 or 0.6.91

**Comment by Jacques00** [comment]
Can you be a bit more specific? 

If you mean your character is not being immobilized, then is your character a goo? Characters with a goo lower body cannot be immobilized or otherwise be effected by the endowment conditions.

**Comment by MillaSteele** [comment]
it seems the Nuki nuts perk is just broken in general. you dont get anything after BlueBalls, your balls size dont change, and your maximum cum doesnt change
