### ISSUE TITLE
Sera's Kids Crash the Game

### ISSUE THREAD

**Issue by JamesDarkholme** [OXOIndustries/Trials-in-Tainted-Space#990]
It seems as though once Sera's kids hit about 3-5 years old the game crashes when you ask Sera to play with them. Also on a seemingly related note, due to it only seeming to occur once Sera's kids hit a certain age, when I move into the room immediately to the right of the Nursery Foyer it becomes impossible to leave forcing me to reload the save. I've managed to get this to happen on several different saves.

**Comment by Jacques00** [comment]
I know the "Play" option has been fixed in #988 , but I'll need a .tits save file to check and see if the crash bug still exists.

**Comment by JamesDarkholme** [comment]
Well, I found the save file, however it won't let me attach it. The save is a .Sol file and I'm not really sure how to get it into a form that I can post here. I'm using Google Chrome if that helps at all.
